# Generated by Django 5.0.4 on 2024-05-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="contact_info",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="freelancerprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="company",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="order_description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="freelancerprofile",
            name="experience",
            field=models.IntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="freelancerprofile",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
